### ISSUE TITLE
duplicate stylesheet names cause issues

### ISSUE THREAD

**Issue by peter-mouland** [bmatcuk/eslint-plugin-postcss-modules#3]
if componentA imports `hero.css`
and componentB imports a completely separate `hero.css` then I get incorrect warnings.

This is in a monorepo.

Has anyone spotted this before?  I can try to build a minimal test case on monday if needed.

**Comment by peter-mouland** [comment]
minimal repo with issue demo'd

https://github.com/peter-mouland/postcss-modules-eslint/tree/master

**Comment by bmatcuk** [comment]
Oops, sounds like a bug... I'll take a look! Hopefully have time today or tomorrow. Thanks for the report, @peter-mouland!

**Comment by bmatcuk** [comment]
### 🎉 v1.1.2 released 🎉 

@peter-mouland: Should solve your issue... seems to work in your test repo. Thank you very much for providing that, by the way! Made it much easier to track down and test!

Let me know if you run into any trouble with it. I'll leave this issue open until I get confirmation that it's working for you =)

**Comment by peter-mouland** [comment]
Amazing, thanks for that, i'll update our repo and let you know 👍

**Comment by bmatcuk** [comment]
You're welcome! Glad to help!
