### ISSUE TITLE
Support composition

### ISSUE THREAD

**Issue by jaydenseric** [bmatcuk/eslint-plugin-postcss-modules#8]
At the moment, the [`composes:` syntax for composition](https://github.com/css-modules/css-modules#composition) is not supported in 2 ways:

1. Falsely reports `composes:` classes as unused. Possibly related to https://github.com/bmatcuk/eslint-plugin-postcss-modules/issues/7 ?
2. The `composes: className from './file.css'` syntax to import specific classes for composition (see the [CSS Modules _“Composing from other files”_ docs](https://github.com/css-modules/css-modules#composing-from-other-files)).

**Comment by jaydenseric** [comment]
Perhaps [`postcss-modules-extract-imports`](https://www.npmjs.com/package/postcss-modules-extract-imports) is part of the solution?

**Comment by bmatcuk** [comment]
Hey @jaydenseric, sorry it's taken so long for me to get to this... been a very busy month for me! Haven't forgotten about these tickets, though!

I've just pushed some changes to the repo that I think will solve the problems with `composes`. Could you give it a try? I haven't officially released via npm yet so you'll need to use the github syntax in your package.json, ie:

```
{
  "devDependencies": {
    "eslint-plugin-postcss-modules": "bmatcuk/eslint-plugin-postcss-modules"
  }
}
```

**Comment by bmatcuk** [comment]
I assume all is well with composition, too? I'm going to close this issue, but let me know if you run into trouble!
